"""Regenerate the two theme-dependent images in web/.

**web/architecture-dark.svg** is a recolour of `web/architecture.svg`. The diagram is loaded with an
img tag, so the page's CSS variables and the site's data-theme attribute never reach inside it, and
a drawing on a near-white ground stayed near-white on a dark page. A prefers-color-scheme block in
the file would not fix that, and would sometimes make it worse: this site defaults to light whatever
the operating system says, so a dark laptop reading a light page would have got a dark diagram. The
theme the reader actually chose is the one the page knows, so common.js does the swap and this only
has to produce the file.

Only the style block is recoloured. Every coordinate, label and path is copied through untouched, so
the two files cannot drift apart in anything but colour. Edit architecture.svg, never the dark one.

**web/social.png** is the Open Graph card. A shared link had no preview at all: no title, no
picture, just a URL. The card carries the name, the one line saying who this is for, and the single
measured number that makes the claim checkable, at the 1200 by 630 Open Graph wants.

    python tools/make_theme_assets.py
"""

from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
WEB = ROOT / "web"
PROJECT = ROOT.name
W, H = 1200, 630

BG, INK, MUTED, RULE = "#FAFAF8", "#1A1A1A", "#5C5C57", "#E4E2DC"

# Left is the light value in the drawing, right is its counterpart in the site's dark palette,
# taken from :root[data-theme="dark"] in web/styles.css rather than invented here.
SWAP = [
    ("#FAFAF8", "#121212"), ("#fff", "#1C1C1C"), ("#F3F2EE", "#262626"),
    ("#E4E2DC", "#2E2E2E"), ("#C9C7C1", "#3A3A3A"), ("#1A1A1A", "#ECECEA"),
    ("#5C5C57", "#A3A39E"), ("#B3261E", "#F26D63"), ("#FBEAE8", "#33201E"),
    ("#0F6E56", "#4CC38A"), ("#E6F2EE", "#14301F"),
]

CARDS = {
    "turnout": {
        "accent": "#B3261E",
        "name": "Turnout",
        "lines": ["Make sure someone", "is coming."],
        "who": "A background agent for volunteer fire and EMS departments.",
        "stat": "3.5x",
        "stat_label": ["coverage failures caught,", "against a roster check"],
    },
    "tally": {
        "accent": "#0F6E56",
        "name": "Tally",
        "lines": ["She has twelve kids", "and no free hands."],
        "who": "A hands-free agent for home child care providers.",
        # 35 of 45 is the honest accuracy figure and the wrong number for a card: at thumbnail
        # size it reads as a mediocre score before anyone reaches the caption. This is the same
        # measurement stated as what it costs her. See docs/EVAL.md, for a home with 6 children
        # at the lower tier.
        "stat": "$101.76",
        "stat_label": ["a month of meals caught at the", "table, not at claim time"],
    },
}


def dark_diagram() -> None:
    svg = (WEB / "architecture.svg").read_text(encoding="utf-8")
    m = re.search(r"<style>(.*?)</style>", svg, re.S)
    if not m:
        raise SystemExit("architecture.svg has no style block to recolour")
    css = m.group(1)
    for light, dark in SWAP:
        css = re.sub(re.escape(light), dark, css, flags=re.I)
    css = "\n    /* Generated by tools/make_theme_assets.py. Edit architecture.svg. */" + css
    out = svg[:m.start(1)] + css + svg[m.end(1):]
    # Arrow markers carry their fill as an attribute rather than a class.
    for light, dark in SWAP:
        out = re.sub(r'(<path d="M 0 0 L 10 5 L 0 10 z" fill=")' + re.escape(light) + r'(")',
                     lambda mo, d=dark: mo.group(1) + d + mo.group(2), out, flags=re.I)
    (WEB / "architecture-dark.svg").write_text(out, encoding="utf-8")
    print("  web/architecture-dark.svg")


def card_svg(c: dict) -> str:
    accent = c["accent"]
    title = "".join(
        f'<text x="72" y="{262 + i * 76}" fill="{INK}" font-size="66" font-weight="700" '
        f'letter-spacing="-1.8">{ln}</text>'
        for i, ln in enumerate(c["lines"]))
    label = "".join(
        f'<text x="1128" y="{344 + i * 26}" fill="{MUTED}" font-size="19" '
        f'text-anchor="end">{ln}</text>'
        for i, ln in enumerate(c["stat_label"]))
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}"
     font-family="Inter, -apple-system, Segoe UI, system-ui, sans-serif">
  <rect x="0" y="0" width="{W}" height="{H}" fill="{BG}"/>
  <rect x="0" y="0" width="{W}" height="10" fill="{accent}"/>
  <text x="72" y="96" fill="{MUTED}" font-size="24" font-weight="600"
        letter-spacing="2.5">AGENTS FOR HUMANS</text>
  <text x="72" y="152" fill="{accent}" font-size="34" font-weight="700"
        letter-spacing="-0.5">{c["name"]}</text>
  {title}
  <text x="72" y="408" fill="{MUTED}" font-size="25">{c["who"]}</text>
  <text x="1128" y="300" fill="{accent}" font-size="76" font-weight="700"
        text-anchor="end" letter-spacing="-2">{c["stat"]}</text>
  {label}
  <line x1="72" y1="486" x2="1128" y2="486" stroke="{RULE}" stroke-width="3"/>
  <text x="72" y="548" fill="{MUTED}" font-size="21">Built with the Strands Agents SDK on Amazon Bedrock</text>
  <rect x="72" y="574" width="120" height="4" fill="{accent}"/>
</svg>
"""


def social() -> None:
    from playwright.sync_api import sync_playwright

    c = CARDS.get(PROJECT)
    if not c:
        raise SystemExit(f"no card defined for {PROJECT!r}")
    svg = WEB / "social.svg"
    svg.write_text(card_svg(c), encoding="utf-8")
    with sync_playwright() as pw:
        b = pw.chromium.launch()
        pg = b.new_page(viewport={"width": W, "height": H}, device_scale_factor=2)
        pg.goto(svg.resolve().as_uri(), wait_until="load")
        pg.wait_for_timeout(400)
        pg.screenshot(path=str(WEB / "social.png"))
        b.close()
    print("  web/social.png")


def main() -> int:
    dark_diagram()
    social()
    return 0


if __name__ == "__main__":
    sys.exit(main())
